name: lint
on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: TSLint (legacy)
        uses: mooyoul/tslint-actions@master
        with:
          token: ${{ github.token }}
          pattern: "**/*.ts"
          project: "tsconfig.json"
          config: "tslint.json"
